apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-image
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-image
  template:
    metadata:
      labels:
        app: test-image
    spec:
      containers:
        - name: test-image
          image: test-image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: test-image-service
spec:
  selector:
    app: test-image
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
  type: LoadBalancer